### ISSUE TITLE
Multiple issues, notably KDE will not properly start and cannot connect to internet after reboot

### ISSUE THREAD

**Issue by Ganju0** [sigboe/GPD-ArchISO#11]
I installed arch via ssh copy and pasting commands from the guide, then installed KDE before my first reboot. Upon reboot I enter the password for my encrypted partition and then the system hangs and does not start up KDE. I can ctrl+alt+Fkey to log in but running "systemctl start sddm" asks me for a log in prompt which results in "authentication complete" but KDE does not start. Ican start KDE as a wayland session by installing "plasma-wayland-session" and "startplasmacompositor" but the desktop is buggy. Attempting to rotate the display results in the settings window becoming distorted and I can't select the option. Possibly related to my other issues, the home folder has none of the usual subfolders like Documents and Pictures and instead contains just the desktop and a couple hidden folders. And the calender, date and time simply read 0. 

And after restarting I'm having issues connecting to internet and downloading packages and pinging websites. When attempting to download a package such as firefox I get the list of packages and download size but typing "y" gives me a never ending scroll of errors saying "error: failed retrieving file [filename] from [mirror name] could not resolve host; [mirror name]. I had this issue on the previous iso and running "cat /etc/hostname" followed by "systemctl restart dhcpcd" would fix the issue until a restart but this is no longer the case.

**Comment by sigboe** [comment]
@joshskidmore did you have experience with KDE? 
@kwshi or maybe you?

**Comment by kwshi** [comment]
I've never tried KDE, so I'm not sure what to do about that.  Regarding internet, I'm not sure I'll be helpful, but how are you connecting to internet to begin with (is it wifi? if so, connman/netctl/wifi-menu/etc.? ethernet?)?

**Comment by Ganju0** [comment]
I connected to WiFi via wifi-menu. Previously I used a USB ethernet dongle because the wpa_supplicant command would give me a message that said it successfully connected but would hang and I'd have to close out

**Comment by joshskidmore** [comment]
I'm also not a KDE expert, but from your description, it seems like you might be missing some standard KDE packages?

Your internet issues might be related to dhcpcd not being started (if you're using wired internet) or the fact that you used wifi-menu to install (why you had internet before the restart), but lost that connection after reboot. I'm not sure what the typical network method is in KDE, but installing, enabling and starting Networanager is the easiest.

Lack of internet could also explain your calendar issue.

**Comment by joshskidmore** [comment]
Try `sudo systemctl enable dhcpcd; sudo systemctl start dhcpcd` to get you're USB ethernet back online.

**Comment by Ganju0** [comment]
sudo systemctl enable dhcpcd; sudo systemctl start 
Got me connected via ethernet but wifi is still down. Ethernet connection persisted after reboot this time too

**Comment by joshskidmore** [comment]
Wifi:

```
# install networkmanager (note: will install gtk/ui packages)
yaourt -S networkmanager network-manager-applet nm-connection-editor

# enable and start networkmanager
sudo systemctl enable NetworkManager
sudo systemctl start NetworkManager

# connect to a wireless network using nmtui
sudo nmtui
  # Activate a Connection -> (choose wi-fi connection) -> Activate -> Back -> Quit

# should be able to disconnect usb hub and/or usb ethernet because wireless is working!
```

**Comment by kwshi** [comment]
Second on the wifi not persisting through reboots; wifi-menu does not autoconnect upon startup, which means perhaps all you need to do is `wifi-menu` connect again for a quick and easy (albeit temporary) solution.  Alternatively, you can `netctl enable <profile-name>` to enable autoconnect upon startup, where you can get profile names with `netctl list`.  Alternatively, you can use networkmanager as suggested above, or, if you'd like something more lightweight, I'd recommend (what I use) connman:

```
$ sudo pacman -S connman
$ connmanctl
> technologies
> enable wifi
> services
> agent on
> connect <service-id>
```

**Comment by joshskidmore** [comment]
@kwshi - (unrelated) - is there a decent connman systray util out there besides cmst? I use connman on the Pi and prefer it on for low-memory devices, but for my laptop, cmst ends up eating more memory than all of NetworkManager and the GTK applet combined.

**Comment by Ganju0** [comment]
connmanctl gives me this error:    Error getting services: The name net.connman was not provided by any .service filesconnmError getting peers: The name net.connman was not provided by any .service filesconnmancError getting technologies: The name net.connman was not provided by any .service filesccon'nmanctl>

Also while reconnecting to wifi via wifi menu was sucessful I got the same error as above and running the systemctl command did not fix it. It only fixed it for ethernet

**Comment by Ganju0** [comment]
I have to install the ARU before I can try networkmanager

**Comment by Ganju0** [comment]
Can't install the AUR either because git clone `https://aur.archlinux.org/cower.git` gives me `git will not execute and completion git exists`

**Comment by Ganju0** [comment]
If I'm being honest, I feel like I must have messed up a step while installing arch in order for me to be having so many problems but I don't know what it was

**Comment by joshskidmore** [comment]
I definitely feel you missed one (or multiple) steps in @sigboe 's guide. I would start from the partition creation steps and try again. It shouldn't take that long, and it will guarantee you won't be regretting a missed step a couple weeks from now!

**Comment by Ganju0** [comment]
The thing is, this isn't my first time installing it, its just my first time with this iso. So if I just install it again, I think I'll make the same mistake again and be back at square one. I wish I had a clue was to what I'm messing up

**Comment by joshskidmore** [comment]
Who guide did you use to install before?  I'm certain that the ISO isn't causing your issues and @sigboe 's wiki is pretty tested - except for the KDE wiki.

With internet, I would suggest resynchronizing pacman (with AUR with AUR in your `/etc/pacman.conf`) using a frontend like yaourt or pacaur. I'd then reinstall all the packages used in the guide and determine  if one of the packages may have been missed (or throws an error). 

As hinted in the guide, none of us are KDE users, so the KDE wiki could be missing a needed package or whatnot. @sigboe's KDE instructions are just the recommended ones from Arch wiki. If you used a guide that worked for you before, I would recommend cross-referencing it with our guide when it comes to the KDE and sddm install.

**Comment by sigboe** [comment]
I did run KDE for almost a month a good while ago. I cant remember having to do any extroardinary step to make it work. 

Also can you try to just run the KDE steps again alone and give us the output?

Have you read here too:  
https://wiki.archlinux.org/index.php/Display_manager

**Comment by kwshi** [comment]
@joshskidmore That's relatable.  Unfortunately, I don't know of a good systray that interfaces with `connman` (I too tried `cmst` for a while after reading something about `connman` itself being fast, but `cmst` not only ended up being bulky but also was buggy and much less reliable).  I ended up just doing all configuration and setup from the terminal.  I call it minimalism, but it's really just laziness.  Anyway, in case you're simply looking for a graphical interface for `connman`, `connman-gtk` seems possibly acceptable, without all the clatter that `cmst` gives.
