### ISSUE TITLE
WiFi Issue

### ISSUE THREAD

**Issue by microdou** [sigboe/GPD-ArchISO#12]
I've experienced WiFi connectivity issue after reboot. I'm writing here my observation so it may help others.

As usual, I used `wifi-menu` to connect to an access point, which generates a network profile under `/etc/netctl/`. Then I customize the profile to add more access information. WiFi is supposed to work the next time I use `wifi-menu` to access the same access point, but for multiple times it does not work!

Instead of using `wifi-menu`, I directly use `sudo netctl start PROFILE`. Again, for multiple times it does not work. But after trying for a while, it works, by checking `ping google.com`.

**So I think it may be a hardware or driver or kernel issue, which is not related to `GPD-ArchISO`.** I'm not sure though.

Edit: I tested it again, and indeed I'm able to start WiFi after ~6 trials. It may also be a router compatibility issue with GPD.

**Comment by sigboe** [comment]
Does `dhcpcd` start at boot? `systemctl enable dhcpcd`
Can you post some info from `dmesg`?

**Comment by microdou** [comment]
@sigboe I checked `systemctl status dhcpcd`, it's inactive.
The weird thing is, dhcpcd seems to behave negatively to WiFi. After `systemctl start dhcpcd` or `systemctl enable dhcpcd`, the command `sudo netctl start PROFILE` no longer works no matter how many times I try.
Once I disable dhcpcd, `systemctl disable dhcpcd`, everything is back to normal: Multiple trials of `sudo netctl start PROFILE` can finally get `WiFi` working.

**Comment by sigboe** [comment]
@microdou Are you using a desktop environment?

**Comment by microdou** [comment]
@sigboe Yes, I'm using KDE. Which part of the info from `dmesg` is useful for diagnosis?

**Comment by sigboe** [comment]
I suggest installing `networkmanager`

    pacman -S networkmanager plasma-nm

then disable dhcpcd and add the applet to the KDE.

I think those instructions are the correct once 😄

**Comment by sigboe** [comment]
hey @microdou did you try networkmanager? 😅

**Comment by microdou** [comment]
@sigboe Yes, I tried. It works, but still needs several trials for a successful connection, which could just be my network's issue. The successful rate is higher though.

But anyway, `networkmanager` is a good option in KDE environment. What's good about it is that it automatically reconnects upon connection failure. :smile:

BTW, `plasma-nm` is already included in `plasma-meta`. Also the service needs to be started by `systemctl enable NetworkManager` or `systemctl start NetworkManager`.

Thanks!

**Comment by sigboe** [comment]
@microdou If you would like to test some upcoming changes, come with feedback and stuff then you can send me an email. To make it harder for bots and crawlers, ill just say that my email is in one of the PKGBUILD files that is posted in the arch package repository that I have done commits to.

**Comment by microdou** [comment]
@sigboe Thanks, I will. I got the address :smile:
