### ISSUE TITLE
KDE installation

### ISSUE THREAD

**Issue by microdou** [sigboe/GPD-ArchISO#13]
The KDE section of WIKI has key steps missing. As a result, `plasma` and `sddm` won't start. It's not an issue of `GPD-ArchISO` itself.

1. **`xorg-server`** package is needed before `plasma` installation!
2. For Xorg to work properly, somehow the Intel video drive `xf86-video-intel` needs to be installed. I'm a little bit confused here, because I suppose the video driver should already be taken care of by `GPD-ArchISO`...
2. I also recommend `plasma-meta` and `kde-applications-meta` (instead of `plasma` and `kde-applications`) if one decides a **full** KDE installation, so that new future KDE packages are automatically included.

In all,
```
$ sudo pacman -S xf86-video-intel xorg-server plasma-meta kde-applications-meta
$ sudo systemctl enable sddm
$ sudo systemctl start sddm
```
and you are all set with a working KDE!

**Comment by sigboe** [comment]
Thank you! I will update the Wiki.

Yeah I think maybe for a beginner the meta packages will help in this case. I imagine KDE switching to Wayland as default soon, that would change what packages are in the group/-meta.
