### ISSUE TITLE
Wiki instruction error - root=

### ISSUE THREAD

**Issue by cawilliamson** [sigboe/GPD-ArchISO#2]
Hi there!

Just running through your guide now and found that in the unencrypted install wiki guide you say to get the UUID of /dev/mmcblk0p2 but the root volume is /dev/mmcblk0p3 - just thought I'd let you know and save some misery! 👍 

EDIT: Also the cut was -f10 rather than -f8 for me.

**Comment by sigboe** [comment]
Thanks, corrected now.

Haven't been able to vet the unencrypted guide the same as the encrypted one.
