### ISSUE TITLE
[WIKI] instruction Encrypted installation missing mkinitpcio hooks

### ISSUE THREAD

**Issue by Nokius** [sigboe/GPD-ArchISO#4]
First thanks for the great work and the instructions 👍 

I found a little issue in the wiki instruction for Encrypted installation

# Configuring boot environment

nano /etc/mkinitpcio.conf

include hooks *encrypt* and *lvm2* in between **block** and **filesystems**

**IMPORTANT!** without this hooks the GPD will not boot as excepted 

Happy holidays 🎅

**Comment by sigboe** [comment]
This is done in the `gpd-setup` [source](https://github.com/sigboe/GPD-ArchISO/blob/master/archlive/airootfs/usr/bin/gpd-setup)

This is done via the command

```bash
sed -i 's/HOOKS=.*"/HOOKS=\"consolefont base udev autodetect keyboard keymap modconf block encrypt lvm2 filesystems fsck\"/g' ${volume}/etc/mkinitcpio.conf
```

Where volume is by default `/mnt` if you dont set it via `-m` argument

**Comment by Nokius** [comment]
odd :-/ 

I followed the steps like 8 times and the fix was to add it manually :s

**Comment by sigboe** [comment]
I'll have this ticket open while I look into it, I am traveling now but I will try to troubleshoot this. Thanks.

**Comment by Nokius** [comment]
@sigboe Thanks for code link Sorry I didn't checked the code at the first place.
I created an PR which should fix the sed issue. 

Have a save trip 🛷

**Comment by sigboe** [comment]
Closed by pull requests #5

Going to rebuild the ISO when I am not just on my phone during travels. So hopefully this evening Europe time

**Comment by Nokius** [comment]
a new build is [here](https://nokius.net/random/GPD/) available

**Comment by sigboe** [comment]
Downloading it now, gonna do a basic test then upload it 😄 

thanks
