### ISSUE TITLE
Updated linux-jwrdegoede

### ISSUE THREAD

**Issue by microdou** [sigboe/GPD-ArchISO#6]
I'm preparing an iso with your repository. I noticed that there are a bunch of new commits to the linux-jwrdegoede settings in https://github.com/njkli/gpd-pocket. Should I use the updated linux-jwrdegoede files in gpd-pocket to get the newest features? Thanks.

**Comment by sigboe** [comment]
What is the reason? Knowing the reason I can better answer your question.

I just posted an ISO just today with a fixed regex script if that was your problem.

Its not really needed to update this iso, as the install will be the newest possible compiled from njkli, and I can send you precompiled newer install files if you want that. 

Even though its not really needed I was going to post an even newer ISO when the njkli repo is updated. But as always the installed install will be updated, the ISO environment doesn't really need to have the newest packages inside.

**Comment by microdou** [comment]
Thanks for the explanation. I just wanted all packages and setting to be the newest. I didn't know that "the installed install will be updated".

**Comment by microdou** [comment]
Awesome new release!

**Comment by sigboe** [comment]
https://github.com/sigboe/GPD-ArchISO/releases/tag/2018.01.05

I was about to close this issue haha, refering to the release above.
