### ISSUE TITLE
[WIKI] Missing packages for wifi-menu in installed system

### ISSUE THREAD

**Issue by microdou** [sigboe/GPD-ArchISO#9]
`wifi-menu` package is available in newly installed system, but fails to work due to a missing dependency `dialog`, which also needs `wpa_supplicant` and `openssl-1.0`.
The fix may be important for those who only have access to WIFI.

**Comment by sigboe** [comment]
This is normal behavior. I can see how its annoying if you require wifi to continue to download packages. Or the cumbersome to use the USB stick to chroot into the install again to fix it. 

btw I made this short tutorial to help with that
https://github.com/sigboe/GPD-ArchISO/wiki/Troubleshooting-encrypted-install-using-live-USB

I will add the `dialog` and `openssl-1.0` suggested packages installed using pacstrap.

**Comment by sigboe** [comment]
Also you have erned your place in the credits at this point! Hope to see more good suggestions like this from you 😄

**Comment by microdou** [comment]
Thanks! I figured it out :smile:
So far it works beautifully! Appreciate the hard work!
